/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://y7tv5cxtkzhcbmj4p6nqj426vu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-pmxuo43k25hxhehirag6ii2jti",
    "oauth": {},
    "Auth": {
        'region': 'us-east-1',
        'userPoolId': 'us-east-1_t5aJHHNs2',
        'userPoolWebClientId': '62ot0ivr7pu7db3bda3b3nq54p', // Generate a client app with no secret
    }
};


export default awsmobile;